plugins:
  - cleanupAttrs: true
  - removeDoctype: true
  - removeXMLProcInst: true
  - removeComments: true
  - removeMetadata: true
  - removeTitle: true
  - removeDesc: true
  - removeUselessDefs: true
  - removeXMLNS: true
  - removeEditorsNSData: true
  - removeEmptyAttrs: true
  - removeHiddenElems: false
  - removeEmptyText: true
  - removeEmptyContainers: true
  - removeViewBox: false
  - cleanupEnableBackground: true
  - minifyStyles: true
  - convertStyleToAttrs: true
  - convertColors: true
  - convertPathData: true
  - convertTransform: true
  - removeUnknownsAndDefaults: true
  - removeNonInheritableGroupAttrs: true
  - removeUselessStrokeAndFill: true
  - removeUnusedNS: true
  - cleanupIDs: true
  - cleanupNumericValues: true
  - cleanupListOfValues: true
  - moveElemsAttrsToGroup: true
  - moveGroupAttrsToElems: true
  - collapseGroups: false
  - mergePaths: true
  - convertShapeToPath: true
  # WARNING DANGER DANGER
  - sortAttrs: false
  - removeDimensions: false
  - removeAttrs: false
  - removeElementsByAttr: false
  - addClassesToSVGElement: false
  - addAttributesToSVGElement: false
  - removeStyleElement: false
  - removeScriptElement: false
